name: Update Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (adjust as needed)
  workflow_dispatch:       # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to v4 (latest version), v2 is outdated
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas jinja2 requests openpyxl

      - name: Run script
        run: python generate_html.py
        env:
          EXCEL_URL: ${{ secrets.EXCEL_URL }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update data" || echo "No changes to commit"
          git push
