name: Update Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas jinja2 requests openpyxl

      - name: Run script
        run: python generate_html.py
        env:
          EXCEL_URL: ${{ secrets.EXCEL_URL }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html full-data.html user-summary.html two-week-summary.html two-week-summary-*.html
          git commit -m "Update data with all pay periods" || echo "No changes to commit"
          git push
