name: Update Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify a version for consistency (e.g., 3.9 used in submit.yml)

      - name: Install dependencies
        run: pip install pandas jinja2 requests  # Removed openpyxl since CSV doesn't need it

      - name: Run script
        run: python generate_html.py
        # No env variables needed since CSV_URL is hardcoded in the script

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html full-data.html user-summary.html two-week-summary.html two-week-summary-*.html submit.html
          git commit -m "Update data with all pay periods" || echo "No changes to commit"
          git push
